import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
await p.goto('http://localhost:8899/index.html', { waitUntil: 'networkidle' });
await p.waitForTimeout(1200);
await p.screenshot({ path: '/home/claude/shot-hero.png' });
await p.evaluate(() => window.scrollTo(0, 848));
await p.waitForTimeout(900);
await p.screenshot({ path: '/home/claude/shot-strip.png' });
await p.evaluate(() => window.scrollTo(0, 1444));
await p.waitForTimeout(900);
await p.screenshot({ path: '/home/claude/shot-seven.png' });
await p.setViewportSize({ width: 390, height: 844 });
await p.evaluate(() => window.scrollTo(0, 0));
await p.waitForTimeout(700);
await p.screenshot({ path: '/home/claude/shot-mobile.png' });
await b.close();
console.log('ok');
