import { chromium } from 'playwright';
const b = await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
const p = await b.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1.5});
await p.goto('http://localhost:8802/shipping.html',{waitUntil:'networkidle'});
await p.evaluate(()=>{const s=document.querySelectorAll('.acc summary')[1]; s.focus();});
await p.evaluate(()=>document.querySelector('footer').scrollIntoView({block:'end'}));
await p.waitForTimeout(400);
const box=await p.evaluate(()=>{const f=document.querySelector('footer').getBoundingClientRect();return Math.round(f.top);});
await p.screenshot({path:'/tmp/ship-bottom.png',clip:{x:0,y:Math.max(0,box-260),width:1440,height:320}});
console.log('footer top',box, await p.evaluate(()=>{const s=document.querySelectorAll('.acc summary')[1];const cs=getComputedStyle(s);return cs.boxShadow+' | bg '+cs.backgroundColor;}));
await b.close();
